using LexFlow.Application.Common.Interfaces;
using LexFlow.Domain.Entities;
using LexFlow.Infrastructure.Ops;
using Microsoft.EntityFrameworkCore;

namespace LexFlow.Infrastructure.Persistence;

/// <summary>
/// Database-First DbContext: entity mappings are Fluent API configurations only
/// (see <see cref="Configurations"/>). Schema is owned exclusively by the
/// lexflow-database DbUp project — EF migrations are never generated or applied
/// from this context (no `dotnet ef migrations add` in any workflow/runbook).
/// </summary>
public sealed class LexFlowDbContext(DbContextOptions<LexFlowDbContext> options)
    : DbContext(options), IUnitOfWork
{
    public DbSet<Tenant> Tenants => Set<Tenant>();
    public DbSet<Branch> Branches => Set<Branch>();
    public DbSet<Department> Departments => Set<Department>();
    public DbSet<Team> Teams => Set<Team>();
    public DbSet<TeamMember> TeamMembers => Set<TeamMember>();
    public DbSet<User> Users => Set<User>();
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Permission> Permissions => Set<Permission>();
    public DbSet<RolePermission> RolePermissions => Set<RolePermission>();
    public DbSet<UserRole> UserRoles => Set<UserRole>();
    public DbSet<UserPermissionGrant> UserPermissionGrants => Set<UserPermissionGrant>();
    public DbSet<UserSession> UserSessions => Set<UserSession>();
    public DbSet<LoginHistory> LoginHistory => Set<LoginHistory>();
    public DbSet<AuditEvent> AuditEvents => Set<AuditEvent>();
    public DbSet<TenantSetting> TenantSettings => Set<TenantSetting>();
    public DbSet<GatewayConfig> GatewayConfigs => Set<GatewayConfig>();
    public DbSet<TaxConfig> TaxConfigs => Set<TaxConfig>();
    public DbSet<NumberSeries> NumberSeries => Set<NumberSeries>();
    public DbSet<CommTemplate> CommTemplates => Set<CommTemplate>();
    public DbSet<WorkflowRule> WorkflowRules => Set<WorkflowRule>();
    public DbSet<LeadSource> LeadSources => Set<LeadSource>();
    public DbSet<LostReason> LostReasons => Set<LostReason>();
    public DbSet<Lead> Leads => Set<Lead>();
    public DbSet<LeadActivity> LeadActivities => Set<LeadActivity>();
    public DbSet<LeadStageHistory> LeadStageHistory => Set<LeadStageHistory>();
    public DbSet<LeadImportBatch> LeadImportBatches => Set<LeadImportBatch>();
    public DbSet<Client> Clients => Set<Client>();
    public DbSet<ClientContact> ClientContacts => Set<ClientContact>();
    public DbSet<ClientAddress> ClientAddresses => Set<ClientAddress>();
    public DbSet<ClientIdentityDocument> ClientIdentityDocuments => Set<ClientIdentityDocument>();
    public DbSet<ClientRelationship> ClientRelationships => Set<ClientRelationship>();
    public DbSet<ClientPortalUser> ClientPortalUsers => Set<ClientPortalUser>();
    public DbSet<PracticeArea> PracticeAreas => Set<PracticeArea>();
    public DbSet<Court> Courts => Set<Court>();
    public DbSet<Judge> Judges => Set<Judge>();
    public DbSet<CourtHoliday> CourtHolidays => Set<CourtHoliday>();
    public DbSet<Matter> Matters => Set<Matter>();
    public DbSet<MatterTeamMember> MatterTeamMembers => Set<MatterTeamMember>();
    public DbSet<MatterParty> MatterParties => Set<MatterParty>();
    public DbSet<MatterImportantDate> MatterImportantDates => Set<MatterImportantDate>();
    public DbSet<MatterRelated> MatterRelated => Set<MatterRelated>();
    public DbSet<MatterExpense> MatterExpenses => Set<MatterExpense>();
    public DbSet<MatterStatusHistory> MatterStatusHistory => Set<MatterStatusHistory>();
    public DbSet<CourtCase> CourtCases => Set<CourtCase>();
    public DbSet<CaseStageHistory> CaseStageHistory => Set<CaseStageHistory>();
    public DbSet<Hearing> Hearings => Set<Hearing>();
    public DbSet<HearingOutcome> HearingOutcomes => Set<HearingOutcome>();
    public DbSet<CourtOrder> CourtOrders => Set<CourtOrder>();
    public DbSet<CaseParty> CaseParties => Set<CaseParty>();
    public DbSet<EvidenceItem> EvidenceItems => Set<EvidenceItem>();
    public DbSet<EvidenceCustodyLog> EvidenceCustodyLog => Set<EvidenceCustodyLog>();
    public DbSet<Witness> Witnesses => Set<Witness>();
    public DbSet<ArgumentNote> ArgumentNotes => Set<ArgumentNote>();
    public DbSet<OpsTask> OpsTasks => Set<OpsTask>();
    public DbSet<EventReminder> EventReminders => Set<EventReminder>();
    public DbSet<TaskAssignee> TaskAssignees => Set<TaskAssignee>();
    public DbSet<TaskChecklistItem> TaskChecklistItems => Set<TaskChecklistItem>();
    public DbSet<TaskComment> TaskComments => Set<TaskComment>();
    public DbSet<TaskDependency> TaskDependencies => Set<TaskDependency>();
    public DbSet<TaskTemplate> TaskTemplates => Set<TaskTemplate>();
    public DbSet<TaskTemplateItem> TaskTemplateItems => Set<TaskTemplateItem>();
    public DbSet<CalendarEvent> CalendarEvents => Set<CalendarEvent>();
    public DbSet<EventAttendee> EventAttendees => Set<EventAttendee>();
    public DbSet<RecurrenceException> RecurrenceExceptions => Set<RecurrenceException>();
    public DbSet<ExternalCalendarAccount> ExternalCalendarAccounts => Set<ExternalCalendarAccount>();
    public DbSet<ExternalEventLink> ExternalEventLinks => Set<ExternalEventLink>();
    public DbSet<Notification> Notifications => Set<Notification>();
    public DbSet<WorkflowRun> WorkflowRuns => Set<WorkflowRun>();
    public DbSet<WorkflowEventOutbox> WorkflowEventOutbox => Set<WorkflowEventOutbox>();
    public DbSet<CalendarIcsToken> CalendarIcsTokens => Set<CalendarIcsToken>();
    public DbSet<CalendarItemRow> CalendarItemRows => Set<CalendarItemRow>();
    public DbSet<ReminderDispatchLog> ReminderDispatchLogs => Set<ReminderDispatchLog>();
    public DbSet<Mailbox> Mailboxes => Set<Mailbox>();
    public DbSet<EmailThread> EmailThreads => Set<EmailThread>();
    public DbSet<EmailMessage> EmailMessages => Set<EmailMessage>();
    public DbSet<EmailAttachment> EmailAttachments => Set<EmailAttachment>();
    public DbSet<SmsMessage> SmsMessages => Set<SmsMessage>();
    public DbSet<WhatsappMessage> WhatsappMessages => Set<WhatsappMessage>();
    public DbSet<WhatsappOptin> WhatsappOptins => Set<WhatsappOptin>();
    public DbSet<CallLog> CallLogs => Set<CallLog>();
    public DbSet<ChatChannel> ChatChannels => Set<ChatChannel>();
    public DbSet<ChatMember> ChatMembers => Set<ChatMember>();
    public DbSet<ChatMessage> ChatMessages => Set<ChatMessage>();
    public DbSet<WebhookEvent> WebhookEvents => Set<WebhookEvent>();
    public DbSet<Folder> Folders => Set<Folder>();
    public DbSet<Document> Documents => Set<Document>();
    public DbSet<DocumentVersion> DocumentVersions => Set<DocumentVersion>();
    public DbSet<Tag> Tags => Set<Tag>();
    public DbSet<DocumentTag> DocumentTags => Set<DocumentTag>();
    public DbSet<DocumentPermission> DocumentPermissions => Set<DocumentPermission>();
    public DbSet<DocumentShareLink> DocumentShareLinks => Set<DocumentShareLink>();
    public DbSet<DocumentTemplate> DocumentTemplates => Set<DocumentTemplate>();
    public DbSet<TemplateMergeField> TemplateMergeFields => Set<TemplateMergeField>();
    public DbSet<SignatureEnvelope> SignatureEnvelopes => Set<SignatureEnvelope>();
    public DbSet<SignatureSigner> SignatureSigners => Set<SignatureSigner>();
    public DbSet<DocumentActivity> DocumentActivities => Set<DocumentActivity>();
    public DbSet<DocumentIndexOutbox> DocumentIndexOutbox => Set<DocumentIndexOutbox>();
    public DbSet<ActivityCode> ActivityCodes => Set<ActivityCode>();
    public DbSet<RunningTimer> RunningTimers => Set<RunningTimer>();
    public DbSet<TimeEntry> TimeEntries => Set<TimeEntry>();
    public DbSet<RateCard> RateCards => Set<RateCard>();
    public DbSet<RateCardEntry> RateCardEntries => Set<RateCardEntry>();
    public DbSet<BillingArrangement> BillingArrangements => Set<BillingArrangement>();
    public DbSet<Invoice> Invoices => Set<Invoice>();
    public DbSet<InvoiceLine> InvoiceLines => Set<InvoiceLine>();
    public DbSet<InvoiceTax> InvoiceTaxes => Set<InvoiceTax>();
    public DbSet<InvoiceStatusHistory> InvoiceStatusHistory => Set<InvoiceStatusHistory>();
    public DbSet<Payment> Payments => Set<Payment>();
    public DbSet<PaymentAllocation> PaymentAllocations => Set<PaymentAllocation>();
    public DbSet<CreditNote> CreditNotes => Set<CreditNote>();
    public DbSet<Refund> Refunds => Set<Refund>();
    public DbSet<DunningSchedule> DunningSchedules => Set<DunningSchedule>();
    public DbSet<DunningEvent> DunningEvents => Set<DunningEvent>();
    public DbSet<TrustAccount> TrustAccounts => Set<TrustAccount>();
    public DbSet<TrustLedgerEntry> TrustLedgerEntries => Set<TrustLedgerEntry>();
    public DbSet<TrustReconciliation> TrustReconciliations => Set<TrustReconciliation>();
    public DbSet<TrustReconciliationItem> TrustReconciliationItems => Set<TrustReconciliationItem>();
    public DbSet<KbAct> KbActs => Set<KbAct>();
    public DbSet<KbActSection> KbActSections => Set<KbActSection>();
    public DbSet<KbJudgment> KbJudgments => Set<KbJudgment>();
    public DbSet<KbArticle> KbArticles => Set<KbArticle>();
    public DbSet<KbArticleVersion> KbArticleVersions => Set<KbArticleVersion>();
    public DbSet<KbTag> KbTags => Set<KbTag>();
    public DbSet<KbItemTag> KbItemTags => Set<KbItemTag>();
    public DbSet<KbCollection> KbCollections => Set<KbCollection>();
    public DbSet<KbCollectionItem> KbCollectionItems => Set<KbCollectionItem>();
    public DbSet<KbBookmark> KbBookmarks => Set<KbBookmark>();
    public DbSet<KbMatterPin> KbMatterPins => Set<KbMatterPin>();
    public DbSet<ReportDefinition> ReportDefinitions => Set<ReportDefinition>();
    public DbSet<ReportSchedule> ReportSchedules => Set<ReportSchedule>();
    public DbSet<ReportRun> ReportRuns => Set<ReportRun>();
    public DbSet<RptDimDate> RptDimDates => Set<RptDimDate>();
    public DbSet<RptDimLawyer> RptDimLawyers => Set<RptDimLawyer>();
    public DbSet<RptDimClient> RptDimClients => Set<RptDimClient>();
    public DbSet<RptDimPracticeArea> RptDimPracticeAreas => Set<RptDimPracticeArea>();
    public DbSet<RptFactBilling> RptFactBillings => Set<RptFactBilling>();
    public DbSet<RptFactTime> RptFactTimes => Set<RptFactTime>();
    public DbSet<RptFactMatters> RptFactMatters => Set<RptFactMatters>();
    public DbSet<AiInteraction> AiInteractions => Set<AiInteraction>();
    public DbSet<AiEmbedding> AiEmbeddings => Set<AiEmbedding>();
    public DbSet<AiTenantQuota> AiTenantQuotas => Set<AiTenantQuota>();
    public DbSet<AiTranscription> AiTranscriptions => Set<AiTranscription>();
    public DbSet<PortalSession> PortalSessions => Set<PortalSession>();
    public DbSet<PortalLoginHistory> PortalLoginHistory => Set<PortalLoginHistory>();
    public DbSet<PortalMessageThread> PortalMessageThreads => Set<PortalMessageThread>();
    public DbSet<PortalMessage> PortalMessages => Set<PortalMessage>();
    public DbSet<PortalAppointmentRequest> PortalAppointmentRequests => Set<PortalAppointmentRequest>();
    public DbSet<PortalActivityLog> PortalActivityLog => Set<PortalActivityLog>();
    public DbSet<PaymentGatewaySession> PaymentGatewaySessions => Set<PaymentGatewaySession>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(LexFlowDbContext).Assembly);
        base.OnModelCreating(modelBuilder);
    }
}
