apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lexflow-api.fullname" . }}
  labels:
    {{- include "lexflow-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/slot: {{ .Values.slot }}
  template:
    metadata:
      labels:
        {{- include "lexflow-api.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.aspnetEnvironment | quote }}
            - name: OpenTelemetry__OtlpEndpoint
              value: {{ .Values.env.otlpEndpoint | quote }}
          {{- include "lexflow-api.envFrom" . | nindent 10 }}
          readinessProbe:
            httpGet: { path: /health, port: {{ .Values.api.port }} }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.api.port }} }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
